"""
Local-dev file storage service for document uploads.

Architecture:
- StorageBackend is a Protocol so callers depend on the interface, not the
  concrete implementation. Swapping to S3Backend in Phase 3 requires changing
  only get_storage() and adding the S3 implementation class.

- Storage keys follow the pattern:
    {tenant_id}/{loan_id}/{path_uuid}/{safe_filename}
  Each segment is validated to prevent path traversal. The path_uuid is a
  random UUID generated at upload time — it isolates the file inside the
  tenant/loan namespace without coupling it to the DB document ID.

- LocalStorageBackend resolves every key to an absolute path, then asserts
  the result still sits under the configured base directory. This double-check
  blocks any traversal attempt that survives the segment sanitisation.

Phase 3 TODO: add S3StorageBackend that uses boto3 with presigned URLs.
Set STORAGE_BACKEND=s3 in .env and wire AWS_* credentials in config.py.
"""

import hashlib
import os
import re
import uuid
from pathlib import Path
from typing import Protocol, runtime_checkable


# ── Protocol ──────────────────────────────────────────────────────────────────

@runtime_checkable
class StorageBackend(Protocol):
    def put(self, key: str, data: bytes) -> None: ...
    def get_bytes(self, key: str) -> bytes: ...
    def delete(self, key: str) -> None: ...


# ── Helpers ───────────────────────────────────────────────────────────────────

def compute_sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _safe_segment(value: str) -> str:
    """Remove path separators, dots, and whitespace from a single path segment.

    UUID segments pass through unchanged (they contain only hex and hyphens).
    File names have separators stripped; extension is preserved separately by
    make_storage_key().
    """
    cleaned = re.sub(r"[/\\.\s]", "_", value.strip())
    if not cleaned:
        raise ValueError(f"Invalid path segment: {value!r}")
    return cleaned


def make_storage_key(
    tenant_id: str,
    loan_id: str,
    path_uuid: str,
    filename: str,
) -> str:
    """Build a tenant-isolated, traversal-safe storage key.

    Format: {tenant_id}/{loan_id}/{path_uuid}/{safe_basename}{ext}

    The path_uuid is generated by the upload endpoint — it de-duplicates
    storage keys without depending on the DB-assigned document ID.
    """
    safe_tenant = _safe_segment(tenant_id)
    safe_loan   = _safe_segment(loan_id)
    safe_uuid   = _safe_segment(path_uuid)

    basename = os.path.basename(filename) or "unnamed"
    name_part, ext = os.path.splitext(basename)
    # Allow known safe extensions (alpha + dot only); strip anything else.
    safe_ext  = ext if re.match(r"^\.[a-zA-Z0-9]+$", ext) else ""
    safe_name = _safe_segment(name_part) + safe_ext

    return f"{safe_tenant}/{safe_loan}/{safe_uuid}/{safe_name}"


# ── Local (dev) implementation ─────────────────────────────────────────────────

class LocalStorageBackend:
    """Stores files on the local filesystem under LOCAL_UPLOAD_DIR.

    Not suitable for production or multi-process deployments.
    Phase 3: replace with S3StorageBackend.
    """

    def __init__(self, base_dir: str) -> None:
        self._base = Path(base_dir).resolve()
        self._base.mkdir(parents=True, exist_ok=True)

    def _resolve(self, key: str) -> Path:
        """Resolve key to absolute path and verify it stays under base_dir."""
        target = (self._base / key).resolve()
        if not str(target).startswith(str(self._base)):
            # Should never happen if make_storage_key() was used, but belt-and-suspenders.
            raise PermissionError(f"Path traversal blocked for key: {key!r}")
        return target

    def put(self, key: str, data: bytes) -> None:
        path = self._resolve(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    def get_bytes(self, key: str) -> bytes:
        path = self._resolve(key)
        if not path.exists():
            raise FileNotFoundError(f"Storage key not found: {key!r}")
        return path.read_bytes()

    def delete(self, key: str) -> None:
        path = self._resolve(key)
        if path.exists():
            path.unlink()


# ── Factory ────────────────────────────────────────────────────────────────────

_backend: StorageBackend | None = None


def get_storage() -> StorageBackend:
    """Return the singleton storage backend for this process.

    Reads STORAGE_BACKEND from config at first call and caches the instance.
    Phase 3: add an "s3" branch that returns S3StorageBackend.
    """
    global _backend
    if _backend is None:
        from app.core.config import LOCAL_UPLOAD_DIR, STORAGE_BACKEND
        if STORAGE_BACKEND == "local":
            _backend = LocalStorageBackend(LOCAL_UPLOAD_DIR)
        else:
            raise RuntimeError(
                f"Unknown STORAGE_BACKEND '{STORAGE_BACKEND}'. "
                "Supported values: 'local'. Phase 3 will add 's3'."
            )
    return _backend


def new_path_uuid() -> str:
    """Generate a random UUID to use as the path component for a new upload."""
    return str(uuid.uuid4())
