services:
  postgres:
    image: postgres:16
    container_name: origina-postgres
    environment:
      POSTGRES_USER: origina
      POSTGRES_PASSWORD: origina123
      POSTGRES_DB: originadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
